-- Pseudo MySQL schema for IndexedDB database "geosoft" including all columns

CREATE TABLE `tbl_cancelled_call` (
    `userId` VARCHAR(255),
    `col_client_name` VARCHAR(255),
    `col_care_call` VARCHAR(255),
    `col_client_Id` VARCHAR(255),
    `col_date` VARCHAR(255),
    `col_time` VARCHAR(255),
    `col_cancellation_by` VARCHAR(255),
    `col_reason` VARCHAR(255),
    `col_pay_status` VARCHAR(255),
    `col_invoice` VARCHAR(255),
    `col_note` VARCHAR(255),
    `col_company_Id` VARCHAR(255),
    `dateTime` VARCHAR(255),
    PRIMARY KEY (`userId`)
);

CREATE TABLE `tbl_care_calls` (
    `userId` VARCHAR(255),
    `col_client_Id` VARCHAR(255),
    `col_client_name` VARCHAR(255),
    `col_shift_date` VARCHAR(255),
    `col_care_call` VARCHAR(255),
    `uryyToeSS4` VARCHAR(255),
    `col_carer_Id` VARCHAR(255),
    `col_company_Id` VARCHAR(255),
    `dateTime` VARCHAR(255),
    PRIMARY KEY (`userId`)
);

CREATE TABLE `tbl_client_status_records` (
    `userId` VARCHAR(255),
    `col_client_name` VARCHAR(255),
    `col_reason` VARCHAR(255),
    `col_time` VARCHAR(255),
    `col_note` VARCHAR(255),
    `col_status_color` VARCHAR(255),
    `col_start_date` VARCHAR(255),
    `col_end_date` VARCHAR(255),
    `col_active_date` VARCHAR(255),
    `col_client_Id` VARCHAR(255),
    `col_company_Id` VARCHAR(255),
    `dateTime` VARCHAR(255),
    PRIMARY KEY (`userId`)
);

CREATE TABLE `tbl_clients_medication_records` (
    `med_Id` VARCHAR(255),
    `uryyToeSS4` VARCHAR(255),
    `med_name` VARCHAR(255),
    `med_dosage` VARCHAR(255),
    `med_type` VARCHAR(255),
    `med_support_required` VARCHAR(255),
    `med_package` VARCHAR(255),
    `med_details` VARCHAR(255),
    `date_uploaded` VARCHAR(255),
    `time_uploaded` VARCHAR(255),
    `care_call1` VARCHAR(255),
    `care_call2` VARCHAR(255),
    `care_call3` VARCHAR(255),
    `care_call4` VARCHAR(255),
    `extra_call1` VARCHAR(255),
    `extra_call2` VARCHAR(255),
    `extra_call3` VARCHAR(255),
    `extra_call4` VARCHAR(255),
    `col_extra_visit` VARCHAR(255),
    `monday` VARCHAR(255),
    `tuesday` VARCHAR(255),
    `wednesday` VARCHAR(255),
    `thursday` VARCHAR(255),
    `friday` VARCHAR(255),
    `saturday` VARCHAR(255),
    `sunday` VARCHAR(255),
    `client_startMed` VARCHAR(255),
    `client_endMed` VARCHAR(255),
    `col_fifo` VARCHAR(255),
    `col_occurence` VARCHAR(255),
    `col_period_one` VARCHAR(255),
    `col_period_two` VARCHAR(255),
    `col_taskId` VARCHAR(255),
    `med_colours` VARCHAR(255),
    `visibility` VARCHAR(255),
    `col_path` VARCHAR(255),
    `col_company_Id` VARCHAR(255),
    `dateTime` VARCHAR(255),
    PRIMARY KEY (`med_Id`)
);

CREATE TABLE `tbl_clients_task_records` (
    `client_Id` VARCHAR(255),
    `uryyToeSS4` VARCHAR(255),
    `client_taskName` VARCHAR(255),
    `client_task_details` VARCHAR(255),
    `care_call1` VARCHAR(255),
    `care_call2` VARCHAR(255),
    `care_call3` VARCHAR(255),
    `care_call4` VARCHAR(255),
    `extra_call1` VARCHAR(255),
    `extra_call2` VARCHAR(255),
    `extra_call3` VARCHAR(255),
    `extra_call4` VARCHAR(255),
    `col_extra_visit` VARCHAR(255),
    `monday` VARCHAR(255),
    `tuesday` VARCHAR(255),
    `wednesday` VARCHAR(255),
    `thursday` VARCHAR(255),
    `friday` VARCHAR(255),
    `saturday` VARCHAR(255),
    `sunday` VARCHAR(255),
    `tast_anytimeSession` VARCHAR(255),
    `task_startDate` VARCHAR(255),
    `task_endDate` VARCHAR(255),
    `col_fifo` VARCHAR(255),
    `col_occurence` VARCHAR(255),
    `col_period_one` VARCHAR(255),
    `col_period_two` VARCHAR(255),
    `date_uploaded` VARCHAR(255),
    `time_uploaded` VARCHAR(255),
    `col_taskId` VARCHAR(255),
    `task_colours` VARCHAR(255),
    `visibility` VARCHAR(255),
    `col_path` VARCHAR(255),
    `col_company_Id` VARCHAR(255),
    `dateTime` VARCHAR(255),
    PRIMARY KEY (`client_Id`)
);

CREATE TABLE `tbl_daily_shift_records` (
    `userId` VARCHAR(255),
    `shift_status` VARCHAR(255),
    `shift_date` VARCHAR(255),
    `planned_timeIn` VARCHAR(255),
    `planned_timeOut` VARCHAR(255),
    `shift_start_time` VARCHAR(255),
    `shift_end_time` VARCHAR(255),
    `client_name` VARCHAR(255),
    `uryyToeSS4` VARCHAR(255),
    `col_care_call` VARCHAR(255),
    `client_group` VARCHAR(255),
    `carer_Name` VARCHAR(255),
    `task_note` VARCHAR(255),
    `col_carer_Id` VARCHAR(255),
    `timesheet_date` VARCHAR(255),
    `col_area_Id` VARCHAR(255),
    `col_company_Id` VARCHAR(255),
    `col_call_status` VARCHAR(255),
    `col_carecall_rate` VARCHAR(255),
    `col_miles` VARCHAR(255),
    `col_mileage` VARCHAR(255),
    `col_worked_time` VARCHAR(255),
    `col_client_rate` VARCHAR(255),
    `col_client_payer` VARCHAR(255),
    `col_visit_status` VARCHAR(255),
    `col_visit_confirmation` VARCHAR(255),
    `col_care_call_Id` VARCHAR(255),
    `col_postcode` VARCHAR(255),
    `dateTime` VARCHAR(255),
    PRIMARY KEY (`userId`)
);

CREATE TABLE `tbl_finished_meds` (
    `med_Id` VARCHAR(255),
    `task_name` VARCHAR(255),
    `med_date` VARCHAR(255),
    `task_timeIn` VARCHAR(255),
    `task_note` VARCHAR(255),
    `task_SpecialId` VARCHAR(255),
    `uryyToeSS4` VARCHAR(255),
    `team_1email` VARCHAR(255),
    `team_2email` VARCHAR(255),
    `category` VARCHAR(255),
    `col_dosage` VARCHAR(255),
    `col_carername` VARCHAR(255),
    `col_outcome` VARCHAR(255),
    `care_calls` VARCHAR(255),
    `care_call_days` VARCHAR(255),
    `col_task_status` VARCHAR(255),
    `timesheet_date` VARCHAR(255),
    `col_care_call_Id` VARCHAR(255),
    `col_company_Id` VARCHAR(255),
    `dateTime` VARCHAR(255),
    PRIMARY KEY (`med_Id`)
);

CREATE TABLE `tbl_finished_tasks` (
    `task_Id` VARCHAR(255),
    `task_name` VARCHAR(255),
    `task_date` VARCHAR(255),
    `task_timeIn` VARCHAR(255),
    `task_note` VARCHAR(255),
    `task_SpecialId` VARCHAR(255),
    `uryyToeSS4` VARCHAR(255),
    `team_1email` VARCHAR(255),
    `team_2email` VARCHAR(255),
    `category` VARCHAR(255),
    `col_dosage` VARCHAR(255),
    `col_carername` VARCHAR(255),
    `col_outcome` VARCHAR(255),
    `care_calls` VARCHAR(255),
    `care_call_days` VARCHAR(255),
    `col_task_status` VARCHAR(255),
    `timesheet_date` VARCHAR(255),
    `col_care_call_Id` VARCHAR(255),
    `col_company_Id` VARCHAR(255),
    `dateTime` VARCHAR(255),
    PRIMARY KEY (`task_Id`)
);

CREATE TABLE `tbl_future_planning` (
    `userId` VARCHAR(255),
    `col_first_box` VARCHAR(255),
    `col_second_box` VARCHAR(255),
    `col_third_box` VARCHAR(255),
    `col_fourt_box` VARCHAR(255),
    `col_fift_box` VARCHAR(255),
    `col_sixth_box` VARCHAR(255),
    `col_seventh_box` VARCHAR(255),
    `uryyToeSS4` VARCHAR(255),
    `col_company_Id` VARCHAR(255),
    `dateTime` VARCHAR(255),
    PRIMARY KEY (`userId`)
);

CREATE TABLE `tbl_general_client_form` (
    `userId` VARCHAR(255),
    `client_title` VARCHAR(255),
    `client_first_name` VARCHAR(255),
    `client_last_name` VARCHAR(255),
    `client_middle_name` VARCHAR(255),
    `client_preferred_name` VARCHAR(255),
    `client_email_address` VARCHAR(255),
    `client_referred_to` VARCHAR(255),
    `client_date_of_birth` VARCHAR(255),
    `client_ailment` VARCHAR(255),
    `client_primary_phone` VARCHAR(255),
    `col_second_phone` VARCHAR(255),
    `client_culture_religion` VARCHAR(255),
    `client_sexuality` VARCHAR(255),
    `client_area` VARCHAR(255),
    `client_address_line_1` VARCHAR(255),
    `client_address_line_2` VARCHAR(255),
    `client_city` VARCHAR(255),
    `client_county` VARCHAR(255),
    `client_poster_code` VARCHAR(255),
    `client_country` VARCHAR(255),
    `client_access_details` VARCHAR(255),
    `client_highlights` VARCHAR(255),
    `col_Office_Incharge` VARCHAR(255),
    `clientStart_date` VARCHAR(255),
    `clientEnd_date` VARCHAR(255),
    `uryyToeSS4` VARCHAR(255),
    `client_service` VARCHAR(255),
    `what_is_important_to_me` VARCHAR(255),
    `my_likes_and_dislikes` VARCHAR(255),
    `my_current_condition` VARCHAR(255),
    `my_medical_history` VARCHAR(255),
    `my_physical_health` VARCHAR(255),
    `my_mental_health` VARCHAR(255),
    `how_i_communicate` VARCHAR(255),
    `assistive_equipment_i_use` VARCHAR(255),
    `client_latitude` VARCHAR(255),
    `client_longitude` VARCHAR(255),
    `col_pay_rate` VARCHAR(255),
    `col_swn_number` VARCHAR(255),
    `col_qrcode_path` VARCHAR(255),
    `geolocation` VARCHAR(255),
    `qrcode` VARCHAR(255),
    `col_company_Id` VARCHAR(255),
    `dateTime` VARCHAR(255),
    PRIMARY KEY (`userId`)
);

CREATE TABLE `tbl_goesoft_carers_account` (
    `userId` VARCHAR(255),
    `user_fullname` VARCHAR(255),
    `user_email_address` VARCHAR(255),
    `user_phone_number` VARCHAR(255),
    `user_password` VARCHAR(255),
    `col_cookies_identifier` VARCHAR(255),
    `user_special_Id` VARCHAR(255),
    `status1` VARCHAR(255),
    `status2` VARCHAR(255),
    `carer_deviceId` VARCHAR(255),
    `col_company_Id` VARCHAR(255),
    `dateTime` VARCHAR(255),
    PRIMARY KEY (`userId`)
);

CREATE TABLE `tbl_schedule_calls` (
    `userId` VARCHAR(255),
    `client_name` VARCHAR(255),
    `client_area` VARCHAR(255),
    `col_area_city` VARCHAR(255),
    `col_area_Id` VARCHAR(255),
    `uryyToeSS4` VARCHAR(255),
    `first_carer` VARCHAR(255),
    `first_carer_Id` VARCHAR(255),
    `care_calls` VARCHAR(255),
    `dateTime_in` VARCHAR(255),
    `dateTime_out` VARCHAR(255),
    `col_run_name` VARCHAR(255),
    `col_fifo` VARCHAR(255),
    `col_required_carers` VARCHAR(255),
    `Clientshift_Date` VARCHAR(255),
    `team_resource` VARCHAR(255),
    `timeline_colour` VARCHAR(255),
    `col_visitColor_code` VARCHAR(255),
    `rightTo_display` VARCHAR(255),
    `call_status` VARCHAR(255),
    `bgChange` VARCHAR(255),
    `currMonths` VARCHAR(255),
    `col_occurence` VARCHAR(255),
    `col_period_one` VARCHAR(255),
    `col_period_two` VARCHAR(255),
    `col_pay_status` VARCHAR(255),
    `col_invoice_status` VARCHAR(255),
    `col_company_Id` VARCHAR(255),
    `col_weekly_routine` VARCHAR(255),
    `dateTime` VARCHAR(255),
    PRIMARY KEY (`userId`)
);